### ISSUE TITLE
should only accept a featurecollection of length 1

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-point-on-surface#4]
otherwise what would it do

**Comment by morganherlocker** [comment]
> what would it do

It will return a point that is guaranteed to be on one of the features. I think that is a conceivable use case and I believe it is in line with the OGC standard (not that the standard is an authority, but it is probably what people expect coming from SQLworld).

**Comment by tmcw** [comment]
The first one?

**Comment by morganherlocker** [comment]
any. It should find the closest point on any of the geometries.

**Comment by morganherlocker** [comment]
Changed my mind, what I am describing would be a better fit for geometry collections. Let's plan on adding GC support and dropping FC (throw error if an FC is passed in).
